fix(script): ERROR: missing ) after argument list
Fixes an issue when you are running `yarn bootstrap`

```bash
Got syntax error when running npm start
SyntaxError: missing ) after argument list
```

Source:
https://github.com/TypeStrong/ts-node/issues/891#issuecomment-538591298